version: '3'
services:
  front:
    image: node:16.13.2-alpine
    working_dir: '/app'
    volumes:
      - ../../:/app
      - front-deps:/app/node_modules
    command: sh -c "npm i && mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache && npm run start"
    networks:
      - example-net
    depends_on:
      - mongo

  nginx:
    image: nginx
    ports:
      - 443:443
    volumes:
      - ./nginx/entrypoint.sh:/entrypoint.sh
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf.template
    environment:
      NODE_HOST: http://front:3000
      BACKEND_HOST: https://swapi.dev
    entrypoint: ["/entrypoint.sh"]
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - example-net
    depends_on:
      - front

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "0.0.0.0:27017:27017"
    networks:
      - example-net
    volumes:
      - ./data:/data/db
volumes:
  front-deps:
  data:

networks:
  example-net:
    name: example-net